baseURL = "https://blog.elzapp.com/"
locale = "en-us"
title = "blog.elzapp.com"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "the tech side"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = "https://mastodon.cloud/@elzapp"
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/header.webp"
  recent_posts_number = 2
